/**
 * RadMind AI â€” Complete Normal Template Skeleton Store
 * =====================================================
 * Built from all 77 Supabase normal templates + additional templates provided.
 * Mapped to exact study type dropdown values from STUDY_TYPE_MAP.
 * Coverage: 125/131 study types
 *
 * Usage:
 *   getSkeleton("MRI", "MSK", "Knee") â†’ Skeleton | null
 *   hasSkeleton("CT", "Chest", "Chest") â†’ boolean
 *
 * Place at: lib/skeletons/skeletons.ts
 */

export interface Skeleton {
  title: string;
  technique: string[];
  findings: string[];
  opinion: string;
}

type SkeletonStore = Record<string, Record<string, Record<string, Skeleton>>>;

export const SKELETONS: SkeletonStore = {

  CT: {
    "Abdomen and pelvis": {
      "Abdomen": {
        title: "Multislice post contrast CT scan of the abdomen and pelvis with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "The liver is average in size showing homogenous CT density with no focal lesions.",
          "Patent and homogenously enhancing portal vein.",
          "No intra or extra hepatic biliary radicles dilatation.",
          "Normal CT appearance of the spleen, pancreas, suprarenal glands, both kidneys, aorta and IVC.",
          "Regular filling of the urinary bladder showing no stones, masses or diverticulae.",
          "Unremarkable pelvic organs.",
          "No retro-crural, para-aortic or pelvic lymphadenopathy.",
          "No ascites.",
          "Scanned lung bases are clear.",
        ],
        opinion: "Normal study.",
      },
      "Abdomen and pelvis": {
        title: "Multislice post contrast CT scan of the abdomen and pelvis with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "The liver is average in size showing homogenous CT density with no focal lesions.",
          "Patent and homogenously enhancing portal vein.",
          "No intra or extra hepatic biliary radicles dilatation.",
          "Normal CT appearance of the spleen, pancreas, suprarenal glands, both kidneys, aorta and IVC.",
          "Regular filling of the urinary bladder showing no stones, masses or diverticulae.",
          "Unremarkable pelvic organs.",
          "No retro-crural, para-aortic or pelvic lymphadenopathy.",
          "No ascites.",
          "Scanned lung bases are clear.",
        ],
        opinion: "Normal study.",
      },
      "Urinary tract": {
        title: "Multislice non contrast CT scan of the urinary tract with multiplanar and curved reformatted images revealed:",
        technique: [],
        findings: [
          "No urinary radiodense stones detected within the kidneys or along the abdominal or pelvic courses of the ureters or within the urinary bladder.",
          "Both kidneys are of average size showing smooth outline with preserved parenchymal thickness.",
          "No back pressure changes.",
          "Normal non contrast CT appearance of the urinary bladder. No stones, masses or diverticulae.",
          "No ascites.",
          "No other significant abnormality seen.",
        ],
        opinion: "No urolithiasis or back pressure changes.",
      },
      "Urography": {
        title: "Multislice CT scan of the urinary tract before and after IV contrast with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "No urinary radiodense stones detected within the kidneys or along the abdominal or pelvic courses of the ureters or within the urinary bladder.",
          "Both kidneys are of average size showing smooth outline with preserved parenchymal thickness.",
          "No renal back pressure changes.",
          "No urinary pathological calcification.",
          "Normal excretory function of both kidneys.",
          "Normal course and caliber of the ureters.",
          "Normal CT appearance of the urinary bladder. No stones, masses or diverticulae.",
          "No ascites.",
          "No pathologically enlarged lymph nodes.",
          "No other significant abnormality seen at the other examined organs.",
        ],
        opinion: "Normal study.",
      },
      "Virtual colonoscopy": {
        title: "MULTISLICE CT VIRTUAL COLONOSCOPY:",
        technique: [
          "Fasting and adequate preparation was performed followed by rectal injection of air.",
          "Ultra-thin axial CT acquisition was done followed by 2D & 3D reformations of the colon with virtual colonoscopy spot images.",
        ],
        findings: [
          "Normal CT appearance of the different parts of the colon.",
          "Normal mucosal pattern with no polyps, ulceration or diverticulae.",
          "No evidence of sizable masses or pathological mural thickening.",
          "Clear peri-colic fat planes.",
        ],
        opinion: "Normal study.",
      },
      "Virtual gastroscopy": {
        title: "MULTISLICE CT VIRTUAL GASTROSCOPY",
        technique: [
          "Fasting and adequate preparation was performed followed by administration of effervescent.",
          "Ultra-thin axial CT acquisition was done followed by 2D & 3D reformations of the stomach with virtual gastroscopy spot images.",
        ],
        findings: [
          "Normal distensibility of the stomach showing normal mucosal rugae pattern with no polyps, ulceration or diverticulae.",
          "No evidence of hiatus hernia.",
          "Clear peri-gastric fat planes.",
        ],
        opinion: "Normal study.",
      },
      "Enterography": {
        title: "Multislice CT enterography after oral ingestion of 5% mannitol solution and IV low osmolar non-ionic contrast administration in the arterial and portal phase with coronal reformatted images revealed:",
        technique: [],
        findings: [
          "Adequate negative contrast opacification was achieved in the stomach, ileum and colon proximal to the sigmoid part with relatively collapsed jejunal loops.",
          "Normal uniform wall thickness and enhancement of the small bowel loops and colon with no evidence of mural thickening, abnormal pathological wall enhancement, mural masses or luminal obstruction.",
          "Normal appearance of the terminal ileum and ileocaecal junction in particular.",
          "The mesenteric vessels and fat appear unremarkable with no evidence of vascular occlusion, narrowing, mesenteric congestion or infiltration.",
          "No bowel wall vascular malformation could be demonstrated.",
          "No free or encysted abdominal collections.",
          "No pathologically enlarged abdominal lymph nodes.",
          "Normal size liver and spleen with no focal lesions.",
          "Normal appearance of the adrenals, both kidneys, pancreas, aorta, IVC and pelvic organs.",
          "Clear scanned lung bases.",
        ],
        opinion: "Normal study.",
      },
      "Liver volumetry": {
        title: "Multislice multiplanar triphasic CT examination of the abdomen with special emphasis to the liver, CT angiography, CT portography & venography as well as CT volumetry revealed:",
        technique: [],
        findings: [
          "Average sized liver is seen showing smooth outline and diffuse homogenous parenchymal texture. No hepatic focal lesions or dilated intra hepatic biliary radicals.",
          "Normal CT appearance of the spleen, pancreas, suprarenal glands, both kidneys, aorta and I.V.C.",
          "No CT evidence of enlarged abdominal or pelvic lymph nodes.",
          "No ascites.",
          "Clear scanned lung bases.",
        ],
        opinion: "Normal CT study of the abdomen.",
      },
    },

    Chest: {
      "Chest": {
        title: "Multislice post contrast CT scan of the chest with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Both lung fields are clear showing no parenchymal nodules, cavitary lesions, consolidative patches or bronchiectatic changes.",
          "No CT evidence of hilar or mediastinal lymph node enlargement.",
          "No pleural or pericardial collections.",
          "No gross cardiac abnormality.",
          "CT cuts of the upper abdomen are unremarkable.",
        ],
        opinion: "Normal CT scan of the chest.",
      },
      "Chest and abdomen": {
        title: "Multislice post contrast CT scan of the chest, abdomen and pelvis with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "(I) Chest:",
          "Patent central air ways with well inflated both lungs.",
          "Both lung fields are clear showing no parenchymal nodules, cavitary lesions, consolidative patches or bronchiectatic changes.",
          "No CT evidence of hilar or mediastinal lymph node enlargement.",
          "No pleural or pericardial collections seen.",
          "No gross cardiac abnormality.",
          "(II) Abdomen and pelvis:",
          "The liver is average in size showing homogenous CT density with no focal lesions.",
          "Patent and homogenously enhancing portal vein.",
          "No intra or extra hepatic biliary radicles dilatation.",
          "Normal CT appearance of the spleen, pancreas, suprarenal glands, both kidneys, aorta and IVC.",
          "Regular filling of the urinary bladder showing no stones, masses or diverticulae.",
          "Unremarkable other pelvic organs.",
          "No retro-crural, para-aortic or pelvic lymphadenopathy.",
          "No ascites.",
        ],
        opinion: "Normal study.",
      },
      "Chest, abdomen and pelvis": {
        title: "Multislice post contrast CT scan of the chest, abdomen and pelvis with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "(I) Chest:",
          "Patent central air ways with well inflated both lungs.",
          "Both lung fields are clear showing no parenchymal nodules, cavitary lesions, consolidative patches or bronchiectatic changes.",
          "No CT evidence of hilar or mediastinal lymph node enlargement.",
          "No pleural or pericardial collections seen.",
          "No gross cardiac abnormality.",
          "(II) Abdomen and pelvis:",
          "The liver is average in size showing homogenous CT density with no focal lesions.",
          "Patent and homogenously enhancing portal vein.",
          "No intra or extra hepatic biliary radicles dilatation.",
          "Normal CT appearance of the spleen, pancreas, suprarenal glands, both kidneys, aorta and IVC.",
          "Regular filling of the urinary bladder showing no stones, masses or diverticulae.",
          "Unremarkable other pelvic organs.",
          "No retro-crural, para-aortic or pelvic lymphadenopathy.",
          "No ascites.",
        ],
        opinion: "Normal study.",
      },
      "Virtual bronchoscopy": {
        title: "MULTISLICE CT VIRTUAL BRONCHOSCOPY",
        technique: [
          "Ultra-thin axial CT acquisition was done from the skull base to the lower chest followed by MinIP technique and 2D & 3D reformations of the airway.",
        ],
        findings: [
          "Patent airway from the larynx down to the subsegmental bronchi.",
          "Normal CT appearance of the larynx and trachea as well as the major bronchi.",
          "No significant stenosis along the air column.",
          "No endobronchial soft tissue lesions.",
          "Axial cuts of the neck are unremarkable.",
          "Clear both lung fields.",
        ],
        opinion: "Normal study.",
      },
    },

    "Head and Neck": {
      "Brain": {
        title: "Multislice non contrast CT scan of the brain:",
        technique: [],
        findings: [
          "No focal cerebral parenchymal areas of abnormal attenuation value.",
          "No intra or extra axial areas of fresh blood density seen.",
          "No supra or infra tentorial sizable masses.",
          "Normal size and configuration of the cerebral ventricles with no evidence of hydrocephalus or atrophy.",
          "No mid line shift or deformity.",
          "No extra axial collections.",
          "No focal brain stem or cerebellar abnormality.",
        ],
        opinion: "Normal CT scan of the brain.",
      },
      "Neck": {
        title: "Multislice post contrast CT scan of the neck with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Intact aerodigestive air column with no parapharyngeal masses and preserved parapharyngeal fat plains.",
          "Intact laryngeal skeleton with normal appearance of both vocal cords, ary-epiglottic folds and pyriform sinuses.",
          "No glottic, sub-glottic or supra-glottic masses.",
          "Normal appearance of both submandibular glands.",
          "Normal size of the thyroid gland.",
          "Intact carotid sheath vessels.",
          "No pathologically enlarged cervical lymph nodes.",
          "No neck soft tissue mass lesions.",
        ],
        opinion: "Normal CT scan of the neck.",
      },
      "Facial": {
        title: "Multislice CT examination of the skull and facial bones with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Intact facial bones with no evidence of fractures, lytic or sclerotic lesions.",
          "Normal appearance of the mandible.",
          "Clear scanned paranasal sinuses.",
          "Normal appearance of the eye globes.",
          "No soft tissue masses or collection.",
          "Normal appearance of the facial muscles.",
        ],
        opinion: "Normal study.",
      },
      "Skull": {
        title: "Multislice CT examination of the skull and facial bones with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Intact facial bones with no evidence of fractures, lytic or sclerotic lesions.",
          "Normal appearance of the mandible.",
          "Clear scanned paranasal sinuses.",
          "Normal appearance of the eye globes.",
          "No soft tissue masses or collection.",
          "Normal appearance of the facial muscles.",
        ],
        opinion: "Normal study.",
      },
      "Paranasal": {
        title: "Multislice CT scan of the paranasal sinuses revealed:",
        technique: [],
        findings: [
          "Clear both maxillary antra, frontal and sphenoid sinuses as well as the ethmoid air cells.",
          "No air fluid levels.",
          "Patent ostiomeatal units and sphenoethmoidal recesses.",
          "Intact bony boundaries of the paranasal sinuses.",
          "No significant bony nasal septum deviation.",
          "No sizable nasopharyngeal masses.",
        ],
        opinion: "Normal study.",
      },
      "Orbits": {
        title: "MRI OF THE ORBITS",
        technique: ["Multiplanar multisequence study using T1, T2 and fat suppression techniques."],
        findings: [
          "Normal appearance of the optic nerves, eye globes, extra ocular muscles, lacrimal glands and retrobulbar fat.",
          "No orbital masses.",
          "Intact orbital boundaries.",
          "Normal size and configuration of the ventricular system.",
          "Normal size and parenchymal signal intensity pattern of the cerebral hemispheres, cerebellum, and brain stem.",
          "No shift of the midline structures.",
          "No intra or extra axial S.O.Ls.",
          "No extra-axial collections.",
        ],
        opinion: "Normal study.",
      },
      "Petrous": {
        title: "MRI OF THE BRAIN & CEREBELLOPONTINE ANGLE",
        technique: ["Multiplanar multisequence study of the brain and both CPA as per protocol."],
        findings: [
          "Normal appearance of the inner ear structures on both sides namely the cochlea, vestibule and semicircular canals.",
          "Normal appearance of the 7th and 8th cranial nerves on both sides.",
          "No sizable cerebellopontine angle masses.",
          "Normal comparable appearance of the internal auditory canals.",
          "The brain parenchyma shows normal signal intensity pattern. The ventricles and sulci are normal and symmetric.",
        ],
        opinion: "Normal MRI of the brain & CPA.",
      },
      "TMJ": {
        title: "Multi-slice CT scan of the temporomandibular joints with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal appearance of both temporo-mandibular joints with intact cortical outline of the articulating bones.",
          "Normal appearance and position of both TMJ with no evidence of dislocation.",
          "Normal appearance of the surrounding musculature.",
          "No fracture lines detected on either side.",
        ],
        opinion: "Normal study.",
      },
    },

    MSK: {
      "Knee": {
        title: "Multislice CT scan of the knee with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal size and configuration of both menisci showing no evidence of tear or degeneration.",
          "Intact cruciates, collateral ligaments and patellar retinaculae as well as the quadriceps and patellar tendons.",
          "Normal marrow signal pattern of the examined bones.",
          "No joint effusion.",
          "Preserved normal articular relations of the tibio-femoral and patello-femoral joints. Preserved articular cartilages.",
          "Intact peri-articular muscles.",
        ],
        opinion: "Normal study.",
      },
      "Shoulder": {
        title: "CT scan of the shoulder with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal appearance of the acromio-clavicular joint with preserved subacromial fat planes.",
          "Normal appearance of the rotator cuff tendons with no evidence of tears or degeneration.",
          "Intact glenohumeral articulation with no sizable joint effusion.",
          "Normal size and signal pattern of the glenoid labrum.",
          "Normal appearance of long head of biceps tendon and its sheath.",
          "Normal marrow signal pattern of the visualized bones.",
        ],
        opinion: "Normal study.",
      },
      "Arm": {
        title: "Multislice CT scan of the [SIDE] arm with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "Elbow": {
        title: "Multislice CT scan of the [SIDE] elbow with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "Forearm": {
        title: "Multislice CT scan of the [SIDE] forearm with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "Wrist": {
        title: "Multislice CT scan of the [SIDE] wrist with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "Hand": {
        title: "Multislice CT scan of the [SIDE] hand with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "Pelvis and hips": {
        title: "Multislice CT scan of the pelvis and both hips with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the pelvic bones and both proximal femora. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "Preserved hip joint spaces bilaterally.",
          "No sizable soft tissue masses or collections.",
        ],
        opinion: "Normal study.",
      },
      "Femur": {
        title: "Multislice CT scan of the [SIDE] femur with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "Leg": {
        title: "Multislice CT scan of the [SIDE] leg with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "Ankle": {
        title: "Multislice CT scan of the [SIDE] ankle with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "Foot": {
        title: "Multislice CT scan of the [SIDE] foot with 3D and multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Normal osseous features of the examined bones. No fractures, lytic or sclerotic lesions.",
          "The muscle groups are of normal CT appearance with preserved intermuscular fat planes.",
          "No sizable masses or cystic lesions.",
          "No articular abnormalities.",
        ],
        opinion: "Normal study.",
      },
    },

    Spine: {
      "Cervical": {
        title: "Multislice CT scan of the cervical spine with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Good alignment of the cervical spine.",
          "Normal dimensions of cervical spinal canal.",
          "Preserved height and signal pattern of the cervical discs.",
          "No CT evidence of disc herniation or significant bulge.",
          "Normal marrow signal of the examined vertebrae.",
          "Intact cranio-cervical articulation.",
          "No para-spinal soft tissue masses or collection.",
        ],
        opinion: "Normal study.",
      },
      "Dorsal": {
        title: "Multislice CT scan of the dorsal spine with 3D & multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Good alignment of the dorsal spine in the supine position.",
          "Normal sagittal diameter of the dorsal spinal canal.",
          "Normal osseous texture of the dorsal vertebrae and their posterior neural elements.",
          "No evidence of disc herniation or significant bulge.",
          "Intact examined facet and costo-vertebral joints.",
          "No para spinal masses or collections.",
        ],
        opinion: "Normal study.",
      },
      "Lumbosacral": {
        title: "Multislice CT scan of the lumbosacral spine with multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Good alignment of the lumbosacral spine.",
          "Normal dimensions of the lumbar spinal canal.",
          "Preserved height of the lumbar discs.",
          "No CT evidence of disc herniation or significant bulge.",
          "Normal marrow signal of the examined vertebral bodies and their posterior neural arches.",
          "Grossly intact examined facet joints.",
          "No para-spinal soft tissue masses or collection.",
        ],
        opinion: "Normal study.",
      },
      "Whole spine": {
        title: "Multislice CT scan of the whole spine with 3D & multiplanar reformatted images revealed:",
        technique: [],
        findings: [
          "Good alignment of the whole spine in the supine position.",
          "Normal sagittal diameter of the spinal canal.",
          "Normal osseous texture of the cervical, dorsal and lumbar vertebrae and their posterior neural elements.",
          "No evidence of disc herniation or significant bulge.",
          "Intact examined facet and costo-vertebral joints.",
          "No para spinal masses or collections.",
        ],
        opinion: "Normal study.",
      },
    },

    Angio: {
      "Cerebral": {
        title: "MULTISLICE CT ANGIOGRAPHY OF THE CEREBRAL VESSELS",
        technique: [
          "Timed multi slice helical CT acquisition with automatic high flow IV non ionic contrast medium infusion to obtain axial sections in arteriographic phase.",
          "The obtained sections were processed to obtain VR&MIP angiographic images.",
        ],
        findings: [
          "The carotid system:",
          "Patent cervical, petrous, cavernous and supraclinoid segments of both internal carotid arteries.",
          "Patent middle and anterior cerebral arteries.",
          "None of these arteries showed stenotic lesions or occlusive manifestations.",
          "The vertebro basilar system:",
          "Patent vertebrobasilar vessels with normal caliber of the contributing arteries.",
          "All the examined brain arteries showed no mural calcifications or aneurysmal changes.",
        ],
        opinion: "Normal CT angiography of the cerebral vessels.",
      },
      "Cerebral and carotid": {
        title: "Multislice CT angiography of the extra and intra cranial carotid and vertebrobasilar arterial systems revealed:",
        technique: [
          "Timed multi slice helical CT acquisition with automatic high flow IV non ionic contrast medium infusion to obtain axial sections in arteriographic phase.",
          "The obtained sections were processed to obtain VR&MIP angiographic images.",
        ],
        findings: [
          "I- The extra cranial carotid arterial system:",
          "Normal caliber and smooth outline of the extra-cranial carotid systems. No evidence of stenotic segments, AVM's, aneurysms or arterial displacement.",
          "In particular the carotid bifurcations appear free.",
          "II- The intra cranial carotid arterial system:",
          "Normal course and caliber of the intracranial portions of both internal carotid as well as the middle and anterior cerebral arteries.",
          "None of these arteries showed stenotic lesions or occlusive manifestations.",
          "III- The vertebro basilar system:",
          "Patent vertebrobasilar vessels with normal caliber of the contributing arteries.",
          "All the examined brain arteries showed no mural calcifications or aneurysmal changes.",
        ],
        opinion: "Normal study.",
      },
      "Aorta": {
        title: "Multislice CT angiography of the thoracic and abdominal aorta after IV contrast administration with coronal, sagittal, multiplanar and 3D reformatting revealed:",
        technique: [
          "Timed multi slice helical CT acquisition with automatic high flow IV non ionic contrast medium infusion to obtain axial sections in arteriographic phase.",
          "The obtained sections were processed to obtain angiographic images.",
        ],
        findings: [
          "I- Thoracic aorta:",
          "Patent ascending thoracic aorta with normal caliber.",
          "Patent aortic arch and descending thoracic aorta.",
          "The aortic arch is seen giving rise to normally ordered arch branches.",
          "No evidence of stenotic segments, or dissection intimal flaps.",
          "II- Abdominal aorta:",
          "Patent abdominal aorta and its major aortic branches namely celiac, superior mesenteric, renal and inferior mesenteric arteries.",
          "No evidence of aortic stenotic segments, aneurysmal dilatation or dissection intimal flaps.",
        ],
        opinion: "Normal CT angiography of the aorta.",
      },
      "Pulmonary": {
        title: "Multislice CT pulmonary angiography with multiplanar reformatted images revealed:",
        technique: [
          "Timed multi slice helical CT acquisition with automatic high flow IV non ionic contrast medium infusion to obtain axial sections in arteriographic phase.",
          "The obtained sections were processed to obtain angiographic images.",
        ],
        findings: [
          "Normal appearance of the pulmonary arterial and venous systems with no evidence of thromboembolism, aneurysmal dilatation or vascular malformations noted on either side.",
          "Both lung fields are clear. No focal pulmonary parenchymatous lesions seen.",
          "No CT evidence of hilar or mediastinal lymph node enlargement.",
          "No pleural or pericardial collections seen.",
          "No gross cardiac abnormality.",
        ],
        opinion: "Normal study.",
      },
      "Mesenteric": {
        title: "MULTISLICE CT ANGIOGRAPHY OF THE MESENTERIC VESSELS",
        technique: [
          "Timed multi slice helical CT acquisition with automatic high flow IV non ionic contrast medium infusion to obtain axial sections in arteriographic phase.",
          "The obtained sections were processed to obtain angiographic images.",
        ],
        findings: [
          "Patent abdominal aorta with no evidence of significant stenotic lesions, aneurysmal dilatation or intra-luminal dissecting flaps.",
          "Patent celiac trunk, both renal and inferior mesenteric arteries.",
          "Patent superior mesenteric artery and its main branches.",
          "Patent main portal vein and its mesenteric and splenic tributaries.",
          "No evidence of vascular occlusion, narrowing, mesenteric congestion or infiltration.",
          "No bowel wall vascular malformation could be demonstrated.",
          "Patent common, external and internal iliac arteries with no tight stenotic lesions.",
        ],
        opinion: "Unremarkable mesenteric CT angiography.",
      },
      "Renal": {
        title: "Multislice CT angiography of the abdominal aorta and renal arteries",
        technique: [
          "Timed multi slice helical CT acquisition with automatic high flow IV non ionic contrast medium infusion was done to obtain axial sections in arteriographic phase.",
          "The obtained sections were processed to obtain coronal and sagittal reformatted and multi-projections MIP images.",
        ],
        findings: [
          "Patent average caliber of the abdominal aorta with smooth intimal outline and normal course. No atherosclerotic changes, aneurysmal dilatation or stenotic lesions.",
          "Each kidney receives a single patent renal artery that arises from the lateral aspect of the aorta, and runs in a normal course to the renal hilum, where each artery shows normal segmental branching.",
          "No stenotic lesions, early pre-hilar segmental branching or aneurysmal changes.",
          "No accessory renal arteries seen.",
          "The kidneys are of normal size and configuration with average parenchymal thickness.",
        ],
        opinion: "Normal CT angiography of the abdominal aorta and renal arteries.",
      },
      "Upper limb": {
        title: "Multislice CT angiography of the thoracic aorta and [SIDE] upper limb arteries and veins revealed:",
        technique: [
          "Timed multi slice helical CT acquisition with automatic high flow IV non ionic contrast medium infusion to obtain axial sections in arteriographic & venographic phases.",
          "The obtained sections were processed to obtain angiographic & venographic images.",
        ],
        findings: [
          "I- AORTIC ARCH:",
          "Normal appearance of the ascending aorta, aortic arch and descending thoracic aorta with no aneurysmal dilatation, stenotic lesion or intimal dissection.",
          "II- UPPER LIMB ARTERIAL AXIS:",
          "Patent average calibered subclavian artery.",
          "Patent average calibered axillary and brachial arteries.",
          "Patent average calibered ulnar and radial arteries.",
          "Patent superficial and deep palmar arches.",
          "III- UPPER LIMB VENOUS AXIS:",
          "Patent cephalic and basilic veins.",
          "Patent brachial, axillary and subclavian veins.",
          "Patent brachio-cephalic vein & SVC.",
        ],
        opinion: "Normal CT angiography of the upper limb.",
      },
      "Lower limb": {
        title: "Multislice CT angiography of the abdominal aorta & both lower limbs",
        technique: [
          "Timed multi slice helical CT acquisition with automatic high flow IV non ionic contrast medium infusion to obtain axial sections in arteriographic phase.",
          "The obtained sections were processed to obtain angiographic images.",
        ],
        findings: [
          "Aorto-iliac segment:",
          "Normal appearance of the infrarenal abdominal aorta and iliac arteries. No significant stenosis, aneurysmal dilatation or dissection.",
          "The right lower limb axis:",
          "Patent common femoral, superficial femoral and deep femoral arteries.",
          "Patent popliteal artery.",
          "Patent infrapopliteal arteries traced down to their distal ends with patent foot segments.",
          "The left lower limb axis:",
          "Patent common femoral, superficial femoral and deep femoral arteries.",
          "Patent popliteal artery.",
          "Patent infrapopliteal arteries traced down to their distal ends with patent foot segments.",
        ],
        opinion: "Normal CT angiography of the lower limbs.",
      },
    },
  },

  MRI: {
    "Abdomen and pelvis": {
      "Abdomen": {
        title: "MRI OF THE ABDOMEN",
        technique: ["Multiple MR sequences were taken in different planes."],
        findings: [
          "Normal size and signal intensity of the liver showing no focal lesions.",
          "No intra or extra hepatic biliary dilatation.",
          "Normal size, shape and signal intensity pattern of the adrenals, pancreas, spleen and both kidneys.",
          "No MR evidence of abdominal soft tissue mass lesions or enlarged lymph node.",
          "Patent major abdominal vascular channels.",
          "No ascites or encysted collections.",
        ],
        opinion: "Normal MRI of the abdomen.",
      },
      "Abdomen and pelvis": {
        title: "MRI OF THE ABDOMEN & PELVIS",
        technique: ["Multiplanar multisequence study using T1, T2 and fat suppression sequences."],
        findings: [
          "Normal size and signal intensity of the liver showing no focal lesions.",
          "No intra or extra hepatic biliary dilatation.",
          "Normal size, shape and signal intensity pattern of the spleen, pancreas and both kidneys.",
          "Fair filling of the urinary bladder showing no filling defects.",
          "Unremarkable other pelvic organs.",
          "No MR evidence of abdominal or pelvic soft tissue mass lesions or enlarged lymph node.",
          "Patent major abdominal and pelvic vascular channels.",
          "No ascites or encysted collections.",
        ],
        opinion: "Normal MRI of the abdomen and pelvis.",
      },
      "Dynamic liver": {
        title: "DYNAMIC MRI OF THE LIVER",
        technique: [
          "Multiplanar multisequences study before and after IV contrast administration with 3D T1 imaging of the liver using dynamic study. Diffusion images and ADC were also obtained.",
        ],
        findings: [
          "Normal size and signal intensity of the liver showing no focal lesions.",
          "No intra or extra hepatic biliary dilatation.",
          "Normal size, shape and signal intensity pattern of the spleen, pancreas and both kidneys.",
          "Patent portal vein and its branches.",
          "No MR evidence of abdominal soft tissue mass lesions or enlarged lymph node.",
          "Patent major abdominal vascular channels.",
          "No ascites or encysted collections.",
        ],
        opinion: "Normal MRI of the liver.",
      },
      "Dynamic pancreas": {
        title: "DYNAMIC MRI OF THE ABDOMEN WITH SPECIAL EMPHASIS ON THE PANCREAS",
        technique: [
          "Multiple MR sequences were taken in different planes pre and post IV contrast administration with dynamic study of the pancreas.",
        ],
        findings: [
          "Normal appearance of the abdomen with no gross solid or cystic masses. Clear peripancreatic fat planes.",
          "The pancreatic duct is not dilated.",
          "Normal size and signal intensity of the liver showing no focal lesions.",
          "No intra or extra hepatic biliary dilatation.",
          "Normal size, shape and signal intensity pattern of the adrenals, spleen and both kidneys.",
          "No MR evidence of abdominal soft tissue mass lesions or enlarged lymph node.",
          "Patent major abdominal vascular channels.",
          "No ascites or encysted collections.",
        ],
        opinion: "Normal MRI of the abdomen with no gross pancreatic abnormality.",
      },
      "Adrenals": {
        title: "MRI OF THE ADRENALS",
        technique: [
          "Axial 4 mm sections with T1 WI and T2 WI (plates 1, 2).",
          "Axial Inphase and Outphase WI (plates 3, 4).",
          "Coronal 4 mm sections with T2 WI (plate 5).",
        ],
        findings: [
          "The adrenal glands on both sides show normal size and signal pattern with no evidence of adrenal masses or cystic lesions.",
          "Both kidneys are normal.",
          "No focal hepatic or splenic lesions.",
          "The aorta, IVC and portal vein all show normal signal void pattern.",
        ],
        opinion: "Normal study of the adrenal glands.",
      },
      "MRCP": {
        title: "MRCP",
        technique: ["Axial T2 and SPAIR", "2D and 3D MRCP"],
        findings: [
          "Normal course and caliber of the common bile duct.",
          "No stones or strictures within the biliary tree.",
          "No significant intrahepatic biliary dilatation.",
          "Normal appearance of the pancreas. The pancreatic duct is not dilated.",
          "Normal size and signal intensity of the liver and spleen showing no focal lesions.",
          "No ascites or encysted collections.",
        ],
        opinion: "Normal MRCP study.",
      },
      "Urography": {
        title: "MRI OF THE URINARY TRACT (MRU)",
        technique: ["Axial T2 and SPAIR", "Coronal T2", "2D and 3D MRU"],
        findings: [
          "Normal size and parenchymal thickness of both kidneys with no back-pressure changes.",
          "Normal course and caliber of the ureters.",
          "No signal void calculi or pathological calcification seen within both kidneys, both ureters or the urinary bladder.",
          "The liver is of average size with homogenous signal. No focal lesions on non enhanced M.R.I. basis.",
          "No intra-hepatic or extra-hepatic biliary radicles dilatation.",
          "Normal size & parenchymal texture of the spleen with no focal lesions seen.",
          "Normal appearance of the pancreas and both supra renals.",
          "No ascites or abdominal collections noted.",
        ],
        opinion: "Normal MRU study.",
      },
      "Enterography": {
        title: "MR ENTEROGRAPHY",
        technique: [
          "Axial T1, T2 and SPAIR WI (plates 1, 2, 3).",
          "Coronal T2 & SPAIR WI (plates 4, 5).",
        ],
        findings: [
          "Adequate opacification was achieved in the ileal bowel loops and colon.",
          "Normal uniform wall thickness of the small bowel loops and colon with no evidence of mural thickening, masses or luminal obstruction.",
          "Normal appearance of the terminal ileum and ileocaecal junction in particular.",
          "Patent abdominal aorta, IVC and major abdominal vascular channels, showing preserved flow void character.",
          "No free or encysted abdominal collections.",
          "No pathologically enlarged abdominal lymph nodes.",
          "Normal appearance of the liver, spleen, adrenals, both kidneys, pancreas, aorta, IVC.",
        ],
        opinion: "No evidence of small or large bowel pathological lesions detected.",
      },
      "Prostate": {
        title: "MULTIPARAMETRIC MRI OF THE PROSTATE",
        technique: [
          "Multiplanar study using T1, T2 and fat suppression techniques with 3D dynamic T1 imaging of the prostate. Diffusion WIs and ADC maps were also obtained.",
        ],
        findings: [
          "Average size of the prostate with preserved zonal anatomy.",
          "No sizable masses or areas of restricted diffusion.",
          "No pathologically enhancing lesion.",
          "Normal appearance of the seminal vesicles.",
          "Normal urinary bladder.",
          "No pathologically enlarged pelvic lymph nodes.",
          "Patent major pelvic vascular channels.",
          "No ascites or encysted collections.",
        ],
        opinion: "Normal MRI of the prostate.",
      },
      "Fistula": {
        title: "MRI OF THE PERIANAL REGION",
        technique: ["Axial T2 and STIR WI", "Coronal T2 and STIR WI", "Sagittal T2 WI"],
        findings: [
          "Normal MRI appearance of the anal sphincters and the anal canal.",
          "No sizable perianal fistulous tracts or fluid collections.",
          "Normal ischioanal fossae.",
          "Unremarkable pelvic organs.",
          "No pelvic collections.",
        ],
        opinion: "No sizable perianal fistulous tract.",
      },
      "Pelvis Female": {
        title: "MRI OF THE PELVIS",
        technique: ["Sagittal T2WI", "Axial T1, T2 and STIR WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Average size of the uterus showing homogenous signal of the myometrium with no focal lesions. Maintained zonal anatomy.",
          "Both ovaries are of normal appearance showing no solid or cystic lesions.",
          "Normal MRI appearance of the urinary bladder.",
          "No evidence of pelvic soft tissue masses or enlarged lymph nodes.",
          "No pelvic ascites or encysted collections.",
          "Preserved flow void character of iliac vessels.",
        ],
        opinion: "Normal study.",
      },
      "Pelvis Male": {
        title: "MRI OF THE PELVIS",
        technique: ["Sagittal T2WI", "Axial T1, T2 and STIR WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Normal MRI appearance of the urinary bladder.",
          "Normal MRI appearance of the prostate and seminal vesicles.",
          "No evidence of pelvic soft tissue masses or enlarged lymph nodes.",
          "No pelvic ascites or encysted collections.",
          "Preserved flow void character of iliac vessels.",
        ],
        opinion: "Normal study.",
      },
    },

    Chest: {
      "Chest": {
        title: "MRI OF THE CHEST & MEDIASTINUM",
        technique: ["Axial T1 & T2-WI (plates 1, 2).", "Coronal T1 & T2 WI (plates 3, 4)."],
        findings: [
          "Normal MRI appearance of the major mediastinal vessels which retains their normal flow-void pattern denoting their patency. No dissecting haematomas or aneurysmal dilatation.",
          "The heart is normal in shape & size its chambers show normal configuration and wall thickness.",
          "No mediastinal masses, collections or lymph node enlargement.",
        ],
        opinion: "Normal study.",
      },
      "Chest and abdomen": {
        title: "MRI OF THE CHEST & ABDOMEN",
        technique: [
          "Chest: Axial T1 & T2-WI (plates 1 & 2). Coronal T1 & T2 WI (plates 3 & 4).",
          "Abdomen: Axial T1, SPAIR & T2 WI (plates 1, 2 & 3). Coronal T2 WI (plate 4).",
        ],
        findings: [
          "Normal MRI appearance of the major mediastinal vessels which retains their normal flow-void pattern denoting their patency. No dissecting haematomas or aneurysmal dilatation.",
          "The heart is normal in shape & size its chambers show normal configuration and wall thickness.",
          "No mediastinal masses, collections or lymph node enlargement.",
          "Normal size, shape and signal intensity pattern of the liver, spleen, pancreas and both kidneys.",
          "No dilated biliary radicles or focal hepatic lesions.",
          "No ascites.",
          "No evidence of abdominal soft tissue mass lesions or enlarged lymph node.",
          "Patent abdominal aorta, IVC and major abdominal vascular channels, showing preserved flow void character.",
        ],
        opinion: "Normal study.",
      },
      "Chest, abdomen and pelvis": {
        title: "MRI OF THE CHEST, ABDOMEN & PELVIS",
        technique: [
          "Chest: Axial T1 & T2-WI (plates 1 & 2). Coronal T1 & T2 WI (plates 3 & 4).",
          "Abdomen: Axial T1, SPAIR & T2 WI (plates 1, 2 & 3). Coronal T2 WI (plate 4).",
          "Pelvis: Sagittal T2WI (plate 1). Axial T1, T2 and STIR WI (plates 2, 3 & 4). Coronal T1, T2 and STIR WI (plates 5, 6 & 7).",
        ],
        findings: [
          "Normal MRI appearance of the major mediastinal vessels which retains their normal flow-void pattern denoting their patency. No dissecting haematomas or aneurysmal dilatation.",
          "The heart is normal in shape & size its chambers show normal configuration and wall thickness.",
          "No mediastinal masses, collections or lymph node enlargement.",
          "Normal size, shape and signal intensity pattern of the liver, spleen, pancreas and both kidneys.",
          "No dilated biliary radicles or focal hepatic lesions.",
          "Normal appearance of the urinary bladder with no masses or diverticular outpouchings.",
          "Unremarkable rest of pelvis organs.",
          "No ascites.",
          "No evidence of abdominal or pelvic soft tissue mass lesions or enlarged lymph node.",
          "Patent abdominal aorta, IVC and major abdominal/pelvic vascular channels, showing preserved flow void character.",
        ],
        opinion: "Normal study.",
      },
    },

    "Head and Neck": {
      "Brain": {
        title: "MRI OF THE BRAIN",
        technique: ["Sagittal T2WI", "Axial T1, T2 and FLAIR WI", "Coronal T2WI"],
        findings: [
          "Normal size and parenchymal signal intensity pattern of the cerebral hemispheres, cerebellum and brain stem.",
          "Normal size and configuration of the ventricular system.",
          "No shift of the midline structures.",
          "No extra-axial collections.",
        ],
        opinion: "Normal MRI of the brain.",
      },
      "Facial": {
        title: "MRI OF THE MAXILLOFACIAL REGION",
        technique: ["Multiple MR sequences were taken in different planes."],
        findings: [
          "Normal appearance of both parotid and submandibular glands.",
          "Normal appearance of the different muscle groups.",
          "Preserved subcutaneous fat planes.",
          "Normal marrow signal pattern of the examined bones.",
          "No sizable soft tissue masses or collections.",
          "No pathologically enlarged lymph nodes.",
        ],
        opinion: "Normal study.",
      },
      "Neck": {
        title: "MRI OF THE NECK",
        technique: ["Multiplanar multisequence study."],
        findings: [
          "Intact aerodigestive air column with no parapharyngeal masses and preserved parapharyngeal fat plains.",
          "Intact laryngeal skeleton with normal appearance of both vocal cords, ary-epiglottic folds and pyriform sinuses.",
          "No glottic, sub-glottic or supra-glottic masses.",
          "Normal appearance of both submandibular glands.",
          "Normal size of the thyroid gland.",
          "Intact carotid sheath vessels.",
          "No pathologically enlarged cervical lymph nodes.",
          "No neck soft tissue mass lesions.",
        ],
        opinion: "Normal MRI of the neck.",
      },
      "Orbits": {
        title: "MRI OF THE ORBITS",
        technique: ["Multiplanar multisequence study using T1, T2 and fat suppression techniques."],
        findings: [
          "Normal appearance of the optic nerves, eye globes, extra ocular muscles, lacrimal glands and retrobulbar fat.",
          "No orbital masses.",
          "Intact orbital boundaries.",
          "Normal size and configuration of the ventricular system.",
          "Normal size and parenchymal signal intensity pattern of the cerebral hemispheres, cerebellum, and brain stem.",
          "No shift of the midline structures.",
          "No intra or extra axial S.O.Ls.",
          "No extra-axial collections.",
        ],
        opinion: "Normal study.",
      },
      "Paranasal": {
        title: "MRI OF THE PARANASAL SINUSES",
        technique: [
          "Sagittal T2 WI of the PNS (plate 1).",
          "Axial T1 & T2WIs of the PNS (plates 2, 3).",
          "Coronal T2WIs (plate 4).",
          "Axial FLAIR WI on the brain (plate 5).",
          "Coronal STIR WI of the PNS (plate 6).",
        ],
        findings: [
          "No evidence of CSF leakage seen within the nasal fossae.",
          "Clear both maxillary antra, ethmoid air cells, frontal and sphenoid sinuses.",
          "Intact bony boundaries of the examined sinuses.",
          "Patent ostiomeatal units and sphenoethmoidal recesses.",
          "Central bony nasal septum.",
          "The examined cuts of the brain are unremarkable.",
        ],
        opinion: "Normal MRI of the paranasal sinuses.",
      },
      "Petrous": {
        title: "MRI OF THE BRAIN & CEREBELLOPONTINE ANGLE",
        technique: ["Multiplanar multisequence study of the brain and both CPA as per protocol."],
        findings: [
          "Normal appearance of the inner ear structures on both sides namely the cochlea, vestibule and semicircular canals.",
          "Normal appearance of the 7th and 8th cranial nerves on both sides.",
          "No sizable cerebellopontine angle masses.",
          "Normal comparable appearance of the internal auditory canals.",
          "The brain parenchyma shows normal signal intensity pattern. The ventricles and sulci are normal and symmetric.",
        ],
        opinion: "Normal MRI of the brain & CPA.",
      },
      "Sella": {
        title: "MRI OF THE BRAIN & SELLA",
        technique: ["Multiplanar multisequence study of the brain with dynamic contrast enhanced study of the sella."],
        findings: [
          "The sella turcica is of normal size with symmetrical appearance of its floor.",
          "The pituitary gland is contained within the sella. Its upper border is concave and shows uniform enhancement after contrast injection. No evidence of pituitary focal lesions or contour deformities.",
          "The pituitary stalk is midline and is normal in size.",
          "The supra-sellar cistern is normal in appearance.",
          "Normal appearance of the third ventricular recesses, optic chiasm, optic nerves and optic tracts.",
          "The brain parenchyma shows normal signal intensity pattern. The ventricles and sulci are normal and symmetric.",
        ],
        opinion: "Normal MRI of the brain & sella.",
      },
      "Brachial Plexus": {
        title: "MRI OF THE BRACHIAL PLEXUS",
        technique: ["Coronal T1, T2 & STIR WIs.", "Axial T1 & T2 WIs.", "Sagittal T2."],
        findings: [
          "Normal MRI appearance of the roots, trunks & cords of the brachial plexus with no evidence of cysts or masses noted along their courses.",
          "Normal appearance of the cervical spinal cord & cervico medullary junction.",
          "Normal vertebral alignment.",
          "Normal marrow signal of cervical vertebrae.",
          "No abnormality detected in the axillary or paraspinal soft tissues.",
        ],
        opinion: "Normal MRI study of the brachial plexus.",
      },
      "TMJ": {
        title: "MRI OF BOTH TEMPORO-MANDIBULAR JOINTS",
        technique: [
          "Sagittal oblique T1, T2 & PD in the open & closed mouth positions.",
          "Coronal T2 in the closed mouth position.",
          "No contrast was given.",
        ],
        findings: [
          "Normal location, shape & signal intensity of the articular discs bilaterally.",
          "Free anterior translation of the condylar processes of the mandible coming to lie beneath the articular eminence on the open mouth position.",
          "Preserved marrow signal & smooth outline of the articulating surfaces.",
          "No evidence of TMJ osteoarthritic change.",
          "No significant joint effusion detected.",
        ],
        opinion: "Normal MRI study of both temporo-mandibular joints.",
      },
    },

    MSK: {
      "Knee": {
        title: "MRI OF THE [SIDE] KNEE",
        technique: [
          "Sagittal T1 WI, T2 WI and PD SPAIR (plates 1-3).",
          "Coronal T1 WI and PD SPAIR (plates 4-5).",
          "Axial PD SPAIR (plate 6).",
        ],
        findings: [
          "Normal size and configuration of both menisci showing no evidence of tear or degeneration.",
          "Intact cruciates, collateral ligaments and patellar retinaculae as well as the quadriceps and patellar tendons.",
          "Normal marrow signal pattern of the examined bones.",
          "No joint effusion.",
          "Preserved normal articular relations of the tibio-femoral and patello-femoral joints. Preserved articular cartilages.",
          "Intact peri-articular muscles.",
        ],
        opinion: "Normal study.",
      },
      "Shoulder": {
        title: "MRI OF THE [SIDE] SHOULDER",
        technique: ["Sagittal T2WI", "Coronal T1, T2 and STIR WI", "Axial GRE WI"],
        findings: [
          "Normal appearance of the acromio-clavicular joint with preserved subacromial fat planes.",
          "Normal appearance of the rotator cuff tendons with no evidence of tears or degeneration.",
          "Intact glenohumeral articulation with no sizable joint effusion.",
          "Normal size and signal pattern of the glenoid labrum.",
          "Normal appearance of long head of biceps tendon and its sheath.",
          "Normal marrow signal pattern of the visualized bones.",
        ],
        opinion: "Normal MRI of the shoulder.",
      },
      "Ankle": {
        title: "MRI OF THE [SIDE] ANKLE",
        technique: ["Axial T1 & T2 WIs", "Sagittal T1, T2 & STIR WIs", "Coronal GE/T2 WIs"],
        findings: [
          "Preserved tibio-talar and sub-talar articular relations.",
          "Normal size and signal pattern of the Achilles tendons.",
          "Normal appearance of the lateral collateral ligaments and the deltoid ligament complex.",
          "The syndesmotic and sinus tarsi ligaments are also appear intact.",
          "Normal appearance of the peri-articular tendons/sheaths complexes.",
          "Normal marrow signal pattern of the articular bones.",
          "No joint effusion.",
          "Normal appearance of the peri-articular musculature.",
        ],
        opinion: "Normal MRI of the ankle joint.",
      },
      "Elbow": {
        title: "MRI OF THE [SIDE] ELBOW",
        technique: ["Sagittal T2WI", "Axial T1 and T2 WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Intact elbow articulations.",
          "Normal appearance of the common flexor and extensor tendons.",
          "Normal signal pattern of the ulnar and radial collateral ligaments.",
          "Normal signal pattern of the examined bones with no evidence of marrow oedema or infiltration.",
          "No evidence of synovial thickening.",
          "No joint effusion.",
        ],
        opinion: "Normal MRI of the elbow.",
      },
      "Wrist": {
        title: "MRI EXAMINATION OF THE [SIDE] WRIST",
        technique: ["Sagittal T2WI", "Axial T1 and T2 WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Intact radio-carpal, inter-carpal and carpo-metacarpal articular relations.",
          "Preserved distal radio-ulnar articular relation.",
          "Preserved scapho-lunate and luno-triquetral distances.",
          "Normal size, configuration and signal pattern of the TFC complex.",
          "Normal appearance of the contents of the carpal tunnel.",
          "Normal flexors and extensors tendons.",
          "Normal marrow signal pattern of the examined bones.",
          "No sizable joint effusion.",
        ],
        opinion: "Normal study.",
      },
      "Hand": {
        title: "MRI EXAMINATION OF THE [SIDE] HAND",
        technique: ["Sagittal T2WI", "Axial T1 and T2 WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Intact carpo-metacarpal, metacarpo-phalangeal and interphalangeal articular relations.",
          "No sizable joint effusion.",
          "Normal marrow signal pattern of the examined bones.",
          "Normal flexors and extensors tendons.",
          "Normal appearance of the collateral ligaments.",
          "No sizable soft tissue masses or collections.",
        ],
        opinion: "Normal study.",
      },
      "Foot": {
        title: "MRI OF THE [SIDE] FOOT",
        technique: ["Axial T1 & T2 WIs", "Sagittal T1, T2 & STIR WIs", "Coronal T2/GE WIs"],
        findings: [
          "Preserved intertarsal, tarsometatarsal and metatarso-phalangeal articular relations.",
          "Normal appearance of the peri-articular tendons/sheaths complexes.",
          "Normal marrow signal pattern of the articular bones.",
          "No joint effusion or synovial thickening.",
          "Normal appearance of the peri-articular musculature.",
        ],
        opinion: "Normal MRI of the foot.",
      },
      "Pelvis and hips": {
        title: "MRI OF THE PELVIS & BOTH HIPS",
        technique: ["Sagittal T2WIs", "Axial T1 and T2 WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Normal marrow signal intensity pattern of both femoral heads, rest of upper femora and scanned pelvic bones. No evidence of marrow oedema or infiltration.",
          "Intact both hip joints with no joint effusion or synovial thickening.",
          "Normal signal and comparable bulk of the different muscle groups around both hip joints.",
          "Preserved fascial fat planes.",
        ],
        opinion: "Normal study.",
      },
      "Femur": {
        title: "MRI OF THE [SIDE] THIGH",
        technique: [
          "Axial 10 mm sections T1 & T2 WI (plates 1, 2).",
          "Coronal 6 mm sections T2 WI (plate 3).",
          "Sagittal 6 mm sections T2 WI (plate 4).",
        ],
        findings: [
          "Normal appearance & signal intensity of the different muscle groups of the thigh with preserved fat planes in-between. No evidence of muscle tears or strain.",
          "No abnormal soft tissue masses or collection detected.",
          "Normal marrow signal of the femur.",
          "Normal major vascular channels of the thigh.",
        ],
        opinion: "Normal MRI of the thigh.",
      },
      "Sacroiliac": {
        title: "MRI OF THE SACROILIAC JOINTS",
        technique: ["Sagittal T2WIs", "Axial STIR, T1 and T2 WI", "Coronal STIR, T1 and T2 WI"],
        findings: [
          "Normal marrow signal intensity pattern of the articulating bones. No evidence of marrow oedema or infiltration.",
          "Intact both sacroiliac joints with no joint effusion.",
          "Intact sacral foramina.",
          "Normal signal and comparable bulk of the different muscle groups around both hip joints.",
        ],
        opinion: "Normal study.",
      },
      "Arm": {
        title: "MRI OF THE [SIDE] ARM",
        technique: ["Sagittal T2WI", "Axial T1 and T2 WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Normal appearance of the different muscle groups of the arm.",
          "Preserved subcutaneous and intermuscular fat planes.",
          "No sizable soft tissue masses or fluid collections.",
          "Normal marrow signal of the visualized bones.",
          "No gross abnormalities related to the neurovascular bundle.",
        ],
        opinion: "Normal study.",
      },
      "Forearm": {
        title: "MRI OF THE [SIDE] FOREARM",
        technique: ["Sagittal T2WI", "Axial T1 and T2 WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Normal appearance of the different muscle groups of the forearm.",
          "Preserved subcutaneous and intermuscular fat planes.",
          "Normal marrow signal of the visualized bones.",
          "No sizable soft tissue masses or fluid collections.",
          "No gross abnormalities related to the neurovascular bundle.",
        ],
        opinion: "Normal study.",
      },
      "Leg": {
        title: "MRI OF THE [SIDE] LEG",
        technique: ["Sagittal T2WI", "Axial T1 and T2 WI", "Coronal T1, T2 and STIR WI"],
        findings: [
          "Normal appearance of the different muscle groups of the leg.",
          "Preserved subcutaneous and intermuscular fat planes.",
          "Normal marrow signal of the visualized bones.",
          "No sizable soft tissue masses or fluid collections.",
          "No gross abnormalities related to the neurovascular bundle.",
        ],
        opinion: "Normal study.",
      },
      "TMJ": {
        title: "MRI OF BOTH TEMPORO-MANDIBULAR JOINTS",
        technique: [
          "Sagittal oblique T1, T2 & PD in the open & closed mouth positions.",
          "Coronal T2 in the closed mouth position.",
          "No contrast was given.",
        ],
        findings: [
          "Normal location, shape & signal intensity of the articular discs bilaterally.",
          "Free anterior translation of the condylar processes of the mandible coming to lie beneath the articular eminence on the open mouth position.",
          "Preserved marrow signal & smooth outline of the articulating surfaces.",
          "No evidence of TMJ osteoarthritic change.",
          "No significant joint effusion detected.",
        ],
        opinion: "Normal MRI study of both temporo-mandibular joints.",
      },
    },

    Spine: {
      "Cervical Spine": {
        title: "MRI OF THE CERVICAL SPINE",
        technique: ["Sagittal T1 and T2 WIs", "Axial GE WIs"],
        findings: [
          "Good alignment of the cervical spine in the supine position.",
          "Normal dimensions of cervical spinal canal.",
          "Preserved height and signal pattern of the cervical discs.",
          "No MR evidence of disc herniation or significant bulge.",
          "Normal size and signal of the cervical cord.",
          "Normal marrow signal of the examined vertebrae.",
          "Intact cranio-cervical articulation.",
          "No para-spinal soft tissue masses or collection.",
        ],
        opinion: "No MR evidence of significant disc lesions or neural compromise.",
      },
      "Dorsal Spine": {
        title: "MRI OF THE DORSAL SPINE",
        technique: ["Sagittal T1 and T2 WIs", "Axial T2 WIs"],
        findings: [
          "Good alignment of the dorsal spine in the supine position.",
          "Normal dimensions of the dorsal spinal canal.",
          "Preserved height and signal of the dorsal discs.",
          "No MR evidence of disc herniation or significant bulge.",
          "Normal size and signal of the dorsal cord.",
          "Normal marrow signal of the examined vertebral bodies and their posterior neural arches.",
          "Grossly intact examined facet joints.",
          "No para-spinal soft tissue masses or collection.",
        ],
        opinion: "Normal MRI of the dorsal spine.",
      },
      "Lumbar Spine": {
        title: "MRI OF THE LUMBOSACRAL SPINE",
        technique: ["Sagittal T1 and T2 WIs", "Axial T2 WIs"],
        findings: [
          "Good alignment of the lumbosacral spine in the supine position.",
          "Normal dimensions of the lumbar spinal canal.",
          "Preserved height and signal of the lumbar discs.",
          "No MR evidence of disc herniation or significant bulge.",
          "Normal size and signal of the conus medullaris.",
          "Normal marrow signal of the examined vertebral bodies and their posterior neural arches.",
          "Grossly intact examined facet joints.",
          "No para-spinal soft tissue masses or collection.",
        ],
        opinion: "No evidence of significant disc lesions or neural compromise.",
      },
      "Whole spine": {
        title: "MRI OF THE WHOLE SPINE",
        technique: ["Sagittal STIR, T1 and T2 WIs", "Axial T1 and T2 WIs"],
        findings: [
          "Good alignment in the supine position.",
          "Normal marrow signal of the examined vertebral bodies and their posterior neural arches.",
          "Normal dimensions of the spinal canal.",
          "Preserved height and signal of the discs.",
          "No MR evidence of disc herniation or significant bulge.",
          "Normal size and signal of the spinal cord.",
          "Grossly intact examined facet joints.",
          "No para-spinal soft tissue masses or collection.",
        ],
        opinion: "Normal MRI of the whole spine.",
      },
    },

    Angio: {
      "MRA Brain": {
        title: "MRI & MRA EXAMINATION OF THE BRAIN",
        technique: ["Sagittal T2WI", "Axial T2 and FLAIR WI", "Coronal T1WI", "TOF MRA"],
        findings: [
          "I- MRI:",
          "Normal size and parenchymal signal intensity pattern of the cerebral hemispheres, cerebellum and brain stem.",
          "Normal size and configuration of the ventricular system.",
          "No shift of the midline structures.",
          "No extra-axial collections.",
          "II- MRA:",
          "Patent normal caliber common carotid and both anterior and middle cerebral arteries. No evidence of stenotic segments, vessel occlusion or vascular malformation.",
          "Patent average caliber of the basilar and both posterior cerebral arteries with no evidence of vessel occlusion or stenotic segments.",
        ],
        opinion: "Normal MRI and MRA study of the brain.",
      },
      "MRV Brain": {
        title: "MRI & MRV EXAMINATION OF THE BRAIN",
        technique: ["Sagittal T2WI", "Axial T2 and FLAIR WI", "Coronal T1WI", "TOF MRV"],
        findings: [
          "I- MRI:",
          "Normal size and parenchymal signal intensity pattern of the cerebral hemispheres, cerebellum and brain stem.",
          "Normal size and configuration of the ventricular system.",
          "No shift of the midline structures.",
          "No extra-axial collections.",
          "II- MRV:",
          "Normal MR appearance of the superficial and deep cerebral veins.",
          "Normal dural venous sinuses of the brain.",
          "No evidence of thrombosis, filling defects or vascular malformation.",
        ],
        opinion: "Normal MRI and MRV study of the brain.",
      },
      "Brain venography": {
        title: "MRI, MRA & MRV EXAMINATION OF THE BRAIN",
        technique: ["Sagittal T2WI", "Axial T2 and FLAIR WI", "Coronal T1WI", "TOF MRA & MRV"],
        findings: [
          "I- MRI:",
          "Normal size and parenchymal signal intensity pattern of the cerebral hemispheres, cerebellum and brain stem.",
          "Normal size and configuration of the ventricular system.",
          "No shift of the midline structures.",
          "No extra-axial collections.",
          "II- MRA:",
          "Patent normal caliber common carotid and both anterior and middle cerebral arteries. No evidence of stenotic segments, vessel occlusion or vascular malformation.",
          "Patent average caliber of the basilar and both posterior cerebral arteries with no evidence of vessel occlusion or stenotic segments.",
          "III- MRV:",
          "Normal MR appearance of the superficial and deep cerebral veins.",
          "Normal dural venous sinuses of the brain.",
          "No evidence of thrombosis, filling defects or vascular malformation.",
        ],
        opinion: "Normal MRI, MRA and MRV study of the brain.",
      },
      "MRA Aorta": {
        title: "MRA OF THE AORTA",
        technique: ["Axial BTFE and T2 WI 5mm sections (plates 1, 2).", "TOF-MRA for the aorta (plates 3, 4)."],
        findings: [
          "I- Thoracic aorta:",
          "Patent ascending aorta with no dissecting intimal flaps or aneurysmal dilatation.",
          "Patent average calibered aortic arch giving rise to three major branches in order, no dissecting intimal flaps or ostial stenosis involving any of its major branches.",
          "Patent average calibered descending aorta. No aneurysmal dilatation or dissecting intimal flaps.",
          "II- Abdominal aorta and its branches:",
          "Patent average calibered supra-renal segment of the abdominal aorta with no significant stenotic lesions, aneurysmal dilatation or dissecting intimal flaps.",
          "Patent celiac trunk, renal and mesenteric arteries with no occlusive or stenotic lesions.",
          "Patent average calibered common iliac, external iliac and internal iliac arteries with no significant stenotic or occlusive segments.",
        ],
        opinion: "Normal MRA of the aorta.",
      },
      "MRA abdomen": {
        title: "MRA OF THE ABDOMEN",
        technique: ["Coronal T2 WI 5mm sections (plate 1).", "TOF-MRA for the aorta (plate 2)."],
        findings: [
          "Patent average calibered abdominal aorta with no significant stenotic lesions.",
          "Patent celiac trunk, renal and mesenteric arteries with no occlusive or stenotic lesions.",
          "Patent average calibered both common iliac, both external iliac and both internal iliac arteries with no significant stenotic or occlusive segments.",
        ],
        opinion: "Normal MRA of the abdomen.",
      },
      "MRA Renal": {
        title: "MRA OF THE RENAL ARTERIES",
        technique: ["Axial T2 WI 5mm sections (plate 1).", "TOF-MRA for the aorta and renal arteries (plates 2, 3)."],
        findings: [
          "Normal appearance of the abdominal aorta & its main branches, no aneurysmal dilatation or mural irregularities.",
          "Both renal arteries appear of normal caliber & outline. Only one main renal artery could be traced supplying the ipsilateral kidney. No MRA evidence of accessory renal arteries.",
          "Normal appearance of both kidneys with clear cortico-medullary differentiation. No back pressure changes or cortical irregularities.",
          "No abnormal retroperitoneal soft tissue lesions or lymph node enlargement.",
          "No ascites.",
        ],
        opinion: "Normal study.",
      },
      "MRA Upper limb": {
        title: "MRA OF BOTH UPPER LIMBS ARTERIES",
        technique: ["Axial T2 WI 5mm sections (plates 1, 2).", "TOF-MRA for right and left upper limb arteries (plates 3, 4)."],
        findings: [
          "I- Right upper limb arterial axis:",
          "Patent average calibered subclavian artery.",
          "Patent average calibered axillary and brachial arteries.",
          "Patent average calibered radial artery.",
          "Patent average calibered ulnar artery.",
          "II- Left upper limb arterial axis:",
          "Patent average calibered subclavian artery.",
          "Patent average calibered axillary and brachial arteries.",
          "Patent average calibered radial artery.",
          "Patent average calibered ulnar artery.",
        ],
        opinion: "Normal MRA of both upper limbs.",
      },
      "MRA Lower limb": {
        title: "MRA OF BOTH LOWER LIMBS ARTERIES",
        technique: ["Coronal T2 WI 5mm sections (plate 1).", "TOF-MRA for the aorta (plate 2)."],
        findings: [
          "I- Abdominal aorta and its branches:",
          "Patent average calibered infrarenal abdominal aorta with no significant stenotic lesions.",
          "Patent average calibered both common iliac, both external iliac and both internal iliac arteries.",
          "II- Right lower limb arterial axis:",
          "Patent common, deep and superficial femoral arteries with no stenotic or occlusive lesions.",
          "Normal appearance of the popliteal artery down to its bifurcation.",
          "Patent anterior tibial, posterior tibial and peroneal arteries down to the level of the ankle joint.",
          "III- Left lower limb arterial axis:",
          "Patent common, deep and superficial femoral arteries with no stenotic or occlusive lesions.",
          "Normal appearance of the popliteal artery down to its bifurcation.",
          "Patent anterior tibial, posterior tibial and peroneal arteries down to the level of the ankle joint.",
        ],
        opinion: "Normal MRA of both lower limbs.",
      },
      "Upper limb venography": {
        title: "MR VENOGRAPHY OF THE UPPER LIMBS",
        technique: ["Coronal T2 WI (plate 1).", "MRV (plates 2 & 3)."],
        findings: [
          "I- RIGHT UPPER VENOUS AXIS:",
          "Patent cephalic and basilic veins.",
          "Patent radial & ulnar veins.",
          "Patent brachial, axillary and subclavian veins.",
          "Patent brachio-cephalic vein & SVC.",
          "II- LEFT UPPER VENOUS AXIS:",
          "Patent cephalic and basilic veins.",
          "Patent radial & ulnar veins.",
          "Patent brachial, axillary and subclavian veins.",
          "Patent brachio-cephalic vein & SVC.",
        ],
        opinion: "Normal MRV of both upper limbs.",
      },
      "Lower limb venography": {
        title: "MR VENOGRAPHY OF THE LOWER LIMBS AND PELVIC VEINS",
        technique: ["Coronal T2 WI (plate 1).", "MRV (plates 2 & 3)."],
        findings: [
          "I- Right lower limbs venous system:",
          "Patent infra-popliteal venae commitants.",
          "Patent popliteal and femoral veins showing normal flow signal.",
          "Patent great saphenous vein.",
          "II- Left lower limbs venous system:",
          "Patent infra-popliteal venae commitants.",
          "Patent popliteal and femoral veins showing normal flow signal.",
          "Patent great saphenous vein.",
          "III- Pelvic veins and IVC:",
          "Patent external iliac veins showing normal MR signal.",
          "Patent common iliac veins showing normal MR signal.",
          "Patent infra-hepatic segment of the IVC.",
        ],
        opinion: "Normal MRV of the lower limb and pelvic veins.",
      },
    },
  },

  "PET CT": {
    "PET CT": {
      "Whole body PET CT": {
        title: "18 F-FDG PET/CT EXAMINATION",
        technique: [
          "A Whole body PET/CT study was obtained from skull base to the mid thigh using a low dose non contrast CT for attenuation correction.",
          "Diagnostic multislice CT examination after IV contrast administration of the same region.",
        ],
        findings: [
          "I. PET/CT Findings:",
          "Physiologic FDG distribution throughout the body with no pathologic FDG uptake characteristic of malignancy.",
          "II. Diagnostic CT Findings:",
          "Clear both lung fields with no pulmonary nodules, acinar or interstitial abnormality.",
          "Normal sized liver showing homogenous parenchyma with no focal lesions.",
          "No pleural, pericardial or peritoneal collections.",
          "No pathologically enlarged lymph nodes.",
          "The spleen, pancreas, adrenals, kidneys, pelvic organs, aorta and IVC appear unremarkable.",
        ],
        opinion: "Physiologic FDG distribution with no evidence of abnormal metabolic activity distinctive for neoplasia.",
      },
    },
  },

  "X-ray": {
    "X-ray": {
      "Chest": {
        title: "Digital radiographic examination of the chest (PA View) revealed:",
        technique: [],
        findings: ["Clear both lung fields and costophrenic angles.", "Normal cardiothoracic ratio."],
        opinion: "Normal chest X-ray.",
      },
      "Abdomen": {
        title: "Digital radiographic examination of the abdomen revealed:",
        technique: [],
        findings: ["Normal distribution of the bowel gases with no fluid levels or dilated loops seen."],
        opinion: "Normal study.",
      },
      "Cervical spine": {
        title: "Digital radiographic examination of the cervical spine revealed:",
        technique: [],
        findings: ["Good alignment.", "Normal appearance of the vertebral bodies & their posterior elements.", "Maintained disc spaces.", "No bony cervical ribs."],
        opinion: "Normal study.",
      },
      "Lumbar spine": {
        title: "Digital radiographic examination of the lumbosacral spine revealed:",
        technique: [],
        findings: ["Good alignment. No signs of spinal instability at the dynamic views.", "Normal osseous features of the lumbar vertebrae.", "Maintained disc spaces.", "Normal apophyseal and both sacroiliac joints."],
        opinion: "Normal study.",
      },
      "Dorsal spine": {
        title: "Digital radiographic examination of the dorsal spine revealed:",
        technique: [],
        findings: ["Good alignment.", "Normal appearance of the dorsal vertebrae.", "Maintained disc spaces.", "No abnormal paraspinal soft tissue shadows."],
        opinion: "Normal study.",
      },
      "Knee": {
        title: "Digital radiographic examination of both knees revealed:",
        technique: [],
        findings: ["Normal osseous texture of the articulating bones.", "Joint spaces are maintained.", "No intra articular calcified loose bodies."],
        opinion: "Normal study.",
      },
      "Shoulder": {
        title: "Digital radiographic examination of the [SIDE] shoulder revealed:",
        technique: [],
        findings: ["Intact glenohumeral & acromioclavicular articulations.", "No bony or articular abnormalities detected."],
        opinion: "Normal study.",
      },
      "Hand": {
        title: "Digital radiographic examination of the [SIDE] hand revealed:",
        technique: [],
        findings: ["No bony or articular abnormalities detected.", "No definite fracture lines seen."],
        opinion: "Normal study.",
      },
      "Wrist": {
        title: "Digital radiographic examination of the [SIDE] wrist revealed:",
        technique: [],
        findings: ["No bony or articular abnormalities detected.", "No definite fracture lines seen."],
        opinion: "Normal study.",
      },
      "Foot": {
        title: "Digital radiographic examination of the [SIDE] foot revealed:",
        technique: [],
        findings: ["No bony or articular abnormalities detected.", "No definite fracture lines seen."],
        opinion: "Normal study.",
      },
      "Ankle": {
        title: "Digital radiographic examination of the [SIDE] ankle revealed:",
        technique: [],
        findings: ["No bony or articular abnormalities detected.", "No definite fracture lines seen."],
        opinion: "Normal study.",
      },
      "Elbow": {
        title: "Digital radiographic examination of the [SIDE] elbow revealed:",
        technique: [],
        findings: ["No bony or articular abnormalities detected.", "No definite fracture lines seen."],
        opinion: "Normal study.",
      },
      "Hips": {
        title: "Digital radiographic examination of the pelvis & both hips revealed:",
        technique: [],
        findings: [
          "Preserved normal articular relations of the hip joints with preserved joint spaces.",
          "Well preserved spherical contour of the femoral heads with no fissuring or structural collapse.",
          "No fracture lines seen.",
          "Intact sacroiliac joints.",
        ],
        opinion: "Normal study.",
      },
      "Skull": {
        title: "Digital radiographic examination of the skull revealed:",
        technique: [],
        findings: [
          "No fracture lines seen.",
          "Normal appearance of the cranial bones and sutures.",
          "Normal size, shape and cortical outline of the sella turcica.",
          "No pathological intra-cranial calcification.",
        ],
        opinion: "Normal study.",
      },
      "PNS": {
        title: "Digital radiographic examination of the paranasal sinuses revealed:",
        technique: [],
        findings: ["Clear anterior group of the para nasal sinuses with no air fluid levels.", "Intact bony boundaries of the paranasal sinuses.", "No septal deviation."],
        opinion: "Normal study.",
      },
      "Nasopharynx": {
        title: "Digital radiographic examination of the nasopharynx revealed:",
        technique: [],
        findings: ["No evidence of enlarged adenoid.", "Normal appearance of the nasopharyngeal air column."],
        opinion: "Normal study.",
      },
      "Sacroiliac joints": {
        title: "Digital radiographic examination of both sacroiliac joints revealed:",
        technique: [],
        findings: ["Preserved joint spaces with smooth articular surfaces."],
        opinion: "Normal study.",
      },
      "TMJ": {
        title: "Digital radiographic examination of the TMJ revealed:",
        technique: [],
        findings: [
          "Maintained joint spaces of the T.M.J. with no evidence of osteoarthritis or periarticular osteophytosis.",
          "No fracture lines are seen.",
          "No periarticular abnormalities.",
        ],
        opinion: "Normal study.",
      },
      "MCUG": {
        title: "ASCENDING AND MICTURATING CYSTOURETHROGRAM (MCUG) REVEALED:",
        technique: [],
        findings: [
          "Normally opacified whole urethral lumen (anterior and posterior parts) showing regular outlines without evidence of persistent filling defects, definite stenosis or diverticular outpouching.",
          "The urinary bladder shows smooth outlines with no trabeculations, diverticular outpouching or intraluminal filling defects.",
          "No vesicoureteric reflux.",
          "Normal post micturation film with no significant residual amount of urine.",
        ],
        opinion: "Normal study.",
      },
      "Long bone": {
        title: "Digital radiographic examination revealed:",
        technique: [],
        findings: ["No bony or articular abnormalities detected.", "No definite fracture lines seen."],
        opinion: "Normal study.",
      },
      "Barium enema": {
        title: "DOUBLE CONTRAST BARIUM ENEMA EXAMINATION REVEALED:",
        technique: [],
        findings: [
          "Free flow of the contrast column throughout different colonic segments without obstruction.",
          "Normal colonic haustral appearance and mucosal pattern.",
          "No evidence of ulceration, filling defects or diverticular disease.",
          "Normal ileo-caecal region.",
          "No masses, mass effects, displacement or infiltration.",
        ],
        opinion: "Normal double contrast barium enema examination.",
      },
      "Barium follow through": {
        title: "BARIUM MEAL FOLLOW THROUGH EXAMINATION REVEALED:",
        technique: [],
        findings: [
          "Free flow of the barium through the stomach, duodenum, jejunal and ileal loops.",
          "No evidence of persistent stricture or caliber changes.",
          "Normal appearance of the mucosal pattern and wall thickness.",
          "Normal appearance of the ileo-caecal junction.",
        ],
        opinion: "Normal barium meal follow through study.",
      },
      "Barium meal": {
        title: "DOUBLE CONTRAST BARIUM MEAL EXAMINATION REVEALED:",
        technique: [],
        findings: [
          "Free flow of the contrast through the stomach with no evidence of obstruction, stricture, filling defects or diverticulae.",
          "Normal mucosal pattern with no detectable ulceration.",
          "Normal duodenal cap and duodenal curve.",
          "No evidence of reflux or hiatus hernia.",
          "Normal appearance of the gastro-esophageal junction.",
        ],
        opinion: "Normal double contrast barium meal study.",
      },
      "Barium swallow": {
        title: "BARIUM SWALLOW EXAMINATION REVEALED:",
        technique: [],
        findings: [
          "Free flow of the contrast through the whole esophageal length with no evidence of obstruction, stricture, filling defects or diverticulae.",
          "Normal mucosal pattern with no detectable ulceration.",
          "No evidence of reflux or hiatus hernia.",
          "Normal appearance of the gastro-esophageal junction.",
        ],
        opinion: "Normal barium swallow study.",
      },
      "Coccyx": {
        title: "Digital radiographic examination of the coccyx revealed:",
        technique: [],
        findings: ["No fracture line seen.", "No abnormal bony or articular changes."],
        opinion: "Normal study.",
      },
      "Heels": {
        title: "Digital radiographic examination of both heels revealed:",
        technique: [],
        findings: ["No bony calcaneal spurs.", "No abnormal bony or articular changes."],
        opinion: "Normal study.",
      },
      "HSG": {
        title: "Water soluble hystro-salpingography examination:",
        technique: [],
        findings: [
          "Smooth filling of the uterine cavity with no evidence of intra uterine adhesions.",
          "Patent both fallopian tubes with immediate free peritoneal spill.",
          "No evidence of pelvic adhesions in the control film.",
        ],
        opinion: "Normal study.",
      },
      "IVP": {
        title: "Digital radiographic examination of the urinary tract & excretory urography revealed:",
        technique: [],
        findings: [
          "No radio-opaque calculi or pathological calcification detected.",
          "Good contrast excretion and concentration by both kidneys, showing normal size, shape and position.",
          "Normal configuration of both pelvicalyceal systems.",
          "Normal course and calibre of both ureters.",
          "Normal cystogram & post voiding film.",
        ],
        opinion: "Normal study.",
      },
      "PUT": {
        title: "Digital radiographic examination of the urinary tract revealed:",
        technique: [],
        findings: ["No radio-opaque calculi or pathological calcifications could be detected."],
        opinion: "Normal study.",
      },
    },
  },

  "Ultrasound": {
    "Ultrasound": {
      "Abdomen": {
        title: "US examination of the abdomen revealed:",
        technique: [],
        findings: [
          "Liver: Normal in size displays uniform homogenous parenchymal texture with smooth regular surface. No focal lesion. No intrahepatic biliary radicles dilatation. Hepatic veins & IVC are not congested. Portal vein is not seen dilated.",
          "Spleen: Normal in size. No focal lesion.",
          "Gall bladder: Average in size with normal wall thickness. No calculi. No biliary mud. No peri-cholecystic fluid collection. CBD is not seen dilated.",
          "Pancreas: Homogenous parenchymal texture with regular outline. No peri-pancreatic fluid collection. No gross masses.",
          "Right kidney: Smooth regular renal outline. Normal renal parenchymal echogenicity with maintained corticomedullary differentiation. No renal calculi. No renal hydronephrosis. No renal cysts.",
          "Left kidney: Smooth regular renal outline. Normal renal parenchymal echogenicity with maintained corticomedullary differentiation. No renal calculi. No renal hydronephrosis. No renal cysts.",
          "Urinary bladder: Normal wall thickness. No masses. No stones. No wall diverticulae.",
          "No abdominal fluid collection.",
          "No abdominal mass detected.",
          "No sizable aortic aneurysm.",
        ],
        opinion: "Normal study.",
      },
      "Pelvis Female": {
        title: "Pelvic US examination revealed:",
        technique: [],
        findings: [
          "Average size AVF uterus of regular contour.",
          "No uterine mass.",
          "Right ovary: No cyst. No solid mass.",
          "Left ovary: No cyst. No solid mass.",
          "No pelvic fluid collection.",
          "No adnexal mass.",
          "Unremarkable urinary bladder.",
        ],
        opinion: "Normal study.",
      },
      "Pelvis Male": {
        title: "Pelvic US examination revealed:",
        technique: [],
        findings: [
          "Urinary bladder: Normal wall thickness. No masses. No stones. No wall diverticulae.",
          "Prostate: Normal size and echogenicity.",
          "No pelvic fluid collection.",
          "No pelvic mass detected.",
        ],
        opinion: "Normal study.",
      },
      "Thyroid": {
        title: "Neck US examination:",
        technique: [],
        findings: [
          "Thyroid gland: Normal size both thyroid lobes and isthmus. Uniform parenchymal texture of the gland. No focal lesion. Normal parenchymal vascularity through the gland.",
          "Parotid glands: Unremarkable.",
          "Submandibular glands: Unremarkable.",
          "No solid or cystic neck masses.",
          "No pathologically enlarged cervical lymphadenopathy.",
          "Unremarkable neck vascular structures.",
        ],
        opinion: "Normal study.",
      },
      "Scrotal": {
        title: "Scrotal colour Doppler examination:",
        technique: [],
        findings: [
          "Rt. testis: Seen in its anatomical location. Uniform homogenous parenchymal texture. No focal lesion. Normal testicular parenchymal vascularity. Normal size epididymis. No increased vascularity. No hydrocele. No scrotal sac hernia.",
          "Lt. testis: Seen in its anatomical location. Uniform homogenous parenchymal texture. No focal lesion. Normal testicular parenchymal vascularity. Normal size epididymis. No increased vascularity. No hydrocele. No scrotal sac hernia.",
          "Colour Doppler study: No dilated pampiniform plexus of veins.",
        ],
        opinion: "Normal study.",
      },
      "LL Arterial Doppler": {
        title: "Colour Doppler examination of [SIDE] lower limb arteries revealed:",
        technique: [],
        findings: [
          "The examined arteries namely; common femoral, superficial femoral and popliteal artery preserves triphasic flow pattern with preserved peak systolic velocity.",
          "The leg arteries namely anterior tibial artery, tibio-peroneal trunk and posterior tibial artery preserves triphasic flow pattern with preserved peak systolic velocity.",
          "Detected flow in the dorsalis pedis and posterior tibial artery at the ankle level.",
        ],
        opinion: "No areas of hemodynamically significant lumen narrowing or total vessel lumen occlusion.",
      },
      "UL Arterial Doppler": {
        title: "Colour Doppler examination of [SIDE] upper limb arteries revealed:",
        technique: [],
        findings: [
          "The examined arteries namely; subclavian, axillary and brachial arteries preserves triphasic flow pattern with preserved peak systolic velocity.",
          "The forearm arteries namely radial and ulnar arteries preserves triphasic flow pattern with preserved peak systolic velocity.",
        ],
        opinion: "No areas of hemodynamically significant lumen narrowing or total vessel lumen occlusion.",
      },
      "LL Venous Doppler": {
        title: "Colour Doppler examination of [SIDE] lower limb venous system:",
        technique: [],
        findings: [
          "The examined veins namely common femoral, superficial femoral and popliteal veins seen of patent compressible lumen with no detected thrombus.",
          "Normal venous flow pattern being spontaneous, unidirectional, phasic with respiration and augments on distal compression.",
          "Patent compressible long saphenous vein with no thrombus detected.",
        ],
        opinion: "No acute DVT of [SIDE] lower limb venous system.",
      },
      "UL Venous Doppler": {
        title: "Colour Doppler examination of [SIDE] upper limb venous system:",
        technique: [],
        findings: [
          "The examined veins namely brachial, axillary and subclavian veins are of patent compressible lumen with no detected thrombus.",
          "Normal venous flow pattern being spontaneous, unidirectional and shows phasic variation with respiration.",
          "No superficial thrombophlebitis.",
        ],
        opinion: "No DVT of the upper limb venous system.",
      },
      "Obstetric": {
        title: "Obstetric US examination revealed:",
        technique: [],
        findings: [
          "Single intrauterine viable fetus.",
          "Normal fetal biometry consistent with gestational age.",
          "Normal fetal anatomy survey.",
          "Normal amniotic fluid index.",
          "Normal placental position.",
        ],
        opinion: "Normal study.",
      },
      "Musculoskeletal": {
        title: "Musculoskeletal US examination revealed:",
        technique: [],
        findings: [
          "Normal appearance of the examined tendons and muscles.",
          "No abnormal fluid collections or bursitis.",
          "Normal cortical outline of the adjacent bones.",
        ],
        opinion: "Normal study.",
      },
      "Breast": {
        title: "Breast US examination revealed:",
        technique: [],
        findings: [
          "Homogenous fibroglandular tissue bilaterally with no focal solid or cystic lesions.",
          "No suspicious microcalcifications.",
          "No pathologically enlarged axillary lymph nodes.",
        ],
        opinion: "Normal study.",
      },
    },
  },
};

export function getSkeleton(modality: string, bodyRegion: string, studyType: string): Skeleton | null {
  return SKELETONS[modality]?.[bodyRegion]?.[studyType] ?? null;
}

export function hasSkeleton(modality: string, bodyRegion: string, studyType: string): boolean {
  return !!getSkeleton(modality, bodyRegion, studyType);
}


